//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ChamadosPro.wbLogin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Cancelamento_PropostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TefMaximidiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TefMaximidiaCancelamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TefInformacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TefVerifica_ClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback cImport_AssociadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cImport_BeneficiarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback cImport_EnderecoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cImport_CartoesOperationCompleted;
        
        private System.Threading.SendOrPostCallback cImport_ContasAdicionaisOperationCompleted;
        
        private System.Threading.SendOrPostCallback cImport_TelefoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback cIncluir_IndicacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cExcluir_Telefone_MaxividaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cVerificaSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cBuscaFonesLogProspectsFonesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdvanceConsultaRetornoOperationCompleted;
        
        private System.Threading.SendOrPostCallback WhatsAppSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback cEnviaXMLAdvanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ChamadosPro.Properties.Settings.Default.ChamadosPro_wbLogin_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Cancelamento_PropostaCompletedEventHandler Cancelamento_PropostaCompleted;
        
        /// <remarks/>
        public event TefMaximidiaCompletedEventHandler TefMaximidiaCompleted;
        
        /// <remarks/>
        public event TefMaximidiaCancelamentoCompletedEventHandler TefMaximidiaCancelamentoCompleted;
        
        /// <remarks/>
        public event TefInformacaoCompletedEventHandler TefInformacaoCompleted;
        
        /// <remarks/>
        public event TefVerifica_ClienteCompletedEventHandler TefVerifica_ClienteCompleted;
        
        /// <remarks/>
        public event cImport_AssociadoCompletedEventHandler cImport_AssociadoCompleted;
        
        /// <remarks/>
        public event cImport_BeneficiarioCompletedEventHandler cImport_BeneficiarioCompleted;
        
        /// <remarks/>
        public event cImport_EnderecoCompletedEventHandler cImport_EnderecoCompleted;
        
        /// <remarks/>
        public event cImport_CartoesCompletedEventHandler cImport_CartoesCompleted;
        
        /// <remarks/>
        public event cImport_ContasAdicionaisCompletedEventHandler cImport_ContasAdicionaisCompleted;
        
        /// <remarks/>
        public event cImport_TelefoneCompletedEventHandler cImport_TelefoneCompleted;
        
        /// <remarks/>
        public event cIncluir_IndicacaoCompletedEventHandler cIncluir_IndicacaoCompleted;
        
        /// <remarks/>
        public event cExcluir_Telefone_MaxividaCompletedEventHandler cExcluir_Telefone_MaxividaCompleted;
        
        /// <remarks/>
        public event cVerificaSenhaCompletedEventHandler cVerificaSenhaCompleted;
        
        /// <remarks/>
        public event cBuscaFonesLogProspectsFonesCompletedEventHandler cBuscaFonesLogProspectsFonesCompleted;
        
        /// <remarks/>
        public event AdvanceConsultaRetornoCompletedEventHandler AdvanceConsultaRetornoCompleted;
        
        /// <remarks/>
        public event WhatsAppSendCompletedEventHandler WhatsAppSendCompleted;
        
        /// <remarks/>
        public event cEnviaXMLAdvanceCompletedEventHandler cEnviaXMLAdvanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cancelamento_Proposta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Cancelamento_Proposta(string Nome, string Cpf) {
            object[] results = this.Invoke("Cancelamento_Proposta", new object[] {
                        Nome,
                        Cpf});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Cancelamento_PropostaAsync(string Nome, string Cpf) {
            this.Cancelamento_PropostaAsync(Nome, Cpf, null);
        }
        
        /// <remarks/>
        public void Cancelamento_PropostaAsync(string Nome, string Cpf, object userState) {
            if ((this.Cancelamento_PropostaOperationCompleted == null)) {
                this.Cancelamento_PropostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelamento_PropostaOperationCompleted);
            }
            this.InvokeAsync("Cancelamento_Proposta", new object[] {
                        Nome,
                        Cpf}, this.Cancelamento_PropostaOperationCompleted, userState);
        }
        
        private void OnCancelamento_PropostaOperationCompleted(object arg) {
            if ((this.Cancelamento_PropostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Cancelamento_PropostaCompleted(this, new Cancelamento_PropostaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TefMaximidia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TefMaximidia(string Numero_cartao, string validade, string CVV2, double valor, ref string Cod_Retorno, ref string Mensagem, ref string Seq_Tef, string cod_campanha, string seq_campanha, string tipo_cliente, string usuario_tef) {
            object[] results = this.Invoke("TefMaximidia", new object[] {
                        Numero_cartao,
                        validade,
                        CVV2,
                        valor,
                        Cod_Retorno,
                        Mensagem,
                        Seq_Tef,
                        cod_campanha,
                        seq_campanha,
                        tipo_cliente,
                        usuario_tef});
            Cod_Retorno = ((string)(results[1]));
            Mensagem = ((string)(results[2]));
            Seq_Tef = ((string)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TefMaximidiaAsync(string Numero_cartao, string validade, string CVV2, double valor, string Cod_Retorno, string Mensagem, string Seq_Tef, string cod_campanha, string seq_campanha, string tipo_cliente, string usuario_tef) {
            this.TefMaximidiaAsync(Numero_cartao, validade, CVV2, valor, Cod_Retorno, Mensagem, Seq_Tef, cod_campanha, seq_campanha, tipo_cliente, usuario_tef, null);
        }
        
        /// <remarks/>
        public void TefMaximidiaAsync(string Numero_cartao, string validade, string CVV2, double valor, string Cod_Retorno, string Mensagem, string Seq_Tef, string cod_campanha, string seq_campanha, string tipo_cliente, string usuario_tef, object userState) {
            if ((this.TefMaximidiaOperationCompleted == null)) {
                this.TefMaximidiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTefMaximidiaOperationCompleted);
            }
            this.InvokeAsync("TefMaximidia", new object[] {
                        Numero_cartao,
                        validade,
                        CVV2,
                        valor,
                        Cod_Retorno,
                        Mensagem,
                        Seq_Tef,
                        cod_campanha,
                        seq_campanha,
                        tipo_cliente,
                        usuario_tef}, this.TefMaximidiaOperationCompleted, userState);
        }
        
        private void OnTefMaximidiaOperationCompleted(object arg) {
            if ((this.TefMaximidiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TefMaximidiaCompleted(this, new TefMaximidiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TefMaximidiaCancelamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TefMaximidiaCancelamento(string Seq_Trans_Cobranca) {
            object[] results = this.Invoke("TefMaximidiaCancelamento", new object[] {
                        Seq_Trans_Cobranca});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TefMaximidiaCancelamentoAsync(string Seq_Trans_Cobranca) {
            this.TefMaximidiaCancelamentoAsync(Seq_Trans_Cobranca, null);
        }
        
        /// <remarks/>
        public void TefMaximidiaCancelamentoAsync(string Seq_Trans_Cobranca, object userState) {
            if ((this.TefMaximidiaCancelamentoOperationCompleted == null)) {
                this.TefMaximidiaCancelamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTefMaximidiaCancelamentoOperationCompleted);
            }
            this.InvokeAsync("TefMaximidiaCancelamento", new object[] {
                        Seq_Trans_Cobranca}, this.TefMaximidiaCancelamentoOperationCompleted, userState);
        }
        
        private void OnTefMaximidiaCancelamentoOperationCompleted(object arg) {
            if ((this.TefMaximidiaCancelamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TefMaximidiaCancelamentoCompleted(this, new TefMaximidiaCancelamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TefInformacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TefInformacao(string Numero_cartao, System.DateTime dia_cobranca, ref string Mensagem, ref string Cod_retorno, ref double Valor_Enviado, ref string Seq_Tef, ref string pago) {
            object[] results = this.Invoke("TefInformacao", new object[] {
                        Numero_cartao,
                        dia_cobranca,
                        Mensagem,
                        Cod_retorno,
                        Valor_Enviado,
                        Seq_Tef,
                        pago});
            Mensagem = ((string)(results[1]));
            Cod_retorno = ((string)(results[2]));
            Valor_Enviado = ((double)(results[3]));
            Seq_Tef = ((string)(results[4]));
            pago = ((string)(results[5]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TefInformacaoAsync(string Numero_cartao, System.DateTime dia_cobranca, string Mensagem, string Cod_retorno, double Valor_Enviado, string Seq_Tef, string pago) {
            this.TefInformacaoAsync(Numero_cartao, dia_cobranca, Mensagem, Cod_retorno, Valor_Enviado, Seq_Tef, pago, null);
        }
        
        /// <remarks/>
        public void TefInformacaoAsync(string Numero_cartao, System.DateTime dia_cobranca, string Mensagem, string Cod_retorno, double Valor_Enviado, string Seq_Tef, string pago, object userState) {
            if ((this.TefInformacaoOperationCompleted == null)) {
                this.TefInformacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTefInformacaoOperationCompleted);
            }
            this.InvokeAsync("TefInformacao", new object[] {
                        Numero_cartao,
                        dia_cobranca,
                        Mensagem,
                        Cod_retorno,
                        Valor_Enviado,
                        Seq_Tef,
                        pago}, this.TefInformacaoOperationCompleted, userState);
        }
        
        private void OnTefInformacaoOperationCompleted(object arg) {
            if ((this.TefInformacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TefInformacaoCompleted(this, new TefInformacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TefVerifica_Cliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TefVerifica_Cliente(string Nome, string Cpf, string Numero_cartao, string Conta, string Agencia, string Cod_Febraban, string Nosso_numero) {
            object[] results = this.Invoke("TefVerifica_Cliente", new object[] {
                        Nome,
                        Cpf,
                        Numero_cartao,
                        Conta,
                        Agencia,
                        Cod_Febraban,
                        Nosso_numero});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TefVerifica_ClienteAsync(string Nome, string Cpf, string Numero_cartao, string Conta, string Agencia, string Cod_Febraban, string Nosso_numero) {
            this.TefVerifica_ClienteAsync(Nome, Cpf, Numero_cartao, Conta, Agencia, Cod_Febraban, Nosso_numero, null);
        }
        
        /// <remarks/>
        public void TefVerifica_ClienteAsync(string Nome, string Cpf, string Numero_cartao, string Conta, string Agencia, string Cod_Febraban, string Nosso_numero, object userState) {
            if ((this.TefVerifica_ClienteOperationCompleted == null)) {
                this.TefVerifica_ClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTefVerifica_ClienteOperationCompleted);
            }
            this.InvokeAsync("TefVerifica_Cliente", new object[] {
                        Nome,
                        Cpf,
                        Numero_cartao,
                        Conta,
                        Agencia,
                        Cod_Febraban,
                        Nosso_numero}, this.TefVerifica_ClienteOperationCompleted, userState);
        }
        
        private void OnTefVerifica_ClienteOperationCompleted(object arg) {
            if ((this.TefVerifica_ClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TefVerifica_ClienteCompleted(this, new TefVerifica_ClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cImport_Associado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cImport_Associado(
                    string numero_vendas, 
                    string id_registro, 
                    string cpf, 
                    string bandeira, 
                    string num_cartao, 
                    string complemen_cartao, 
                    string dia_venc, 
                    string validade, 
                    string nome_titular, 
                    string nome_segurado, 
                    string data_nascimento, 
                    string altura, 
                    string sexo, 
                    string peso, 
                    string tipo_seguro, 
                    string val_MA, 
                    string val_IPA, 
                    string premio, 
                    string operador, 
                    string obs, 
                    string compl_benefic, 
                    string supervisor, 
                    string e_civil, 
                    string extensao, 
                    string e_mail, 
                    string ocupacao, 
                    string rg, 
                    string digito_rg, 
                    string emissor_rg, 
                    string data_emiss_rg, 
                    string master, 
                    string a_express, 
                    string visa, 
                    string diners, 
                    string filhos, 
                    string banco, 
                    string agencia, 
                    string contaban, 
                    string cobranca, 
                    string nosso_numero, 
                    string numero_lote, 
                    string cod_seguradora, 
                    string cod_produto, 
                    string status, 
                    string Obs_Rejeicao, 
                    string hipercard, 
                    string digito_agencia, 
                    string tipo_conta, 
                    string digito_conta, 
                    string nacionalidade, 
                    string tipo_registro, 
                    string cod_rejeicao, 
                    string desc_ocupacao, 
                    string encaminha_para, 
                    string data_venda, 
                    string data_excluido, 
                    string data_vencimento, 
                    string venda_programada, 
                    string campanha, 
                    string pago, 
                    string faixa_renda, 
                    string idligacao, 
                    string agravo, 
                    string numero_proposta_advance, 
                    string plano, 
                    string val_morte_qc, 
                    string data_retorno_advance) {
            object[] results = this.Invoke("cImport_Associado", new object[] {
                        numero_vendas,
                        id_registro,
                        cpf,
                        bandeira,
                        num_cartao,
                        complemen_cartao,
                        dia_venc,
                        validade,
                        nome_titular,
                        nome_segurado,
                        data_nascimento,
                        altura,
                        sexo,
                        peso,
                        tipo_seguro,
                        val_MA,
                        val_IPA,
                        premio,
                        operador,
                        obs,
                        compl_benefic,
                        supervisor,
                        e_civil,
                        extensao,
                        e_mail,
                        ocupacao,
                        rg,
                        digito_rg,
                        emissor_rg,
                        data_emiss_rg,
                        master,
                        a_express,
                        visa,
                        diners,
                        filhos,
                        banco,
                        agencia,
                        contaban,
                        cobranca,
                        nosso_numero,
                        numero_lote,
                        cod_seguradora,
                        cod_produto,
                        status,
                        Obs_Rejeicao,
                        hipercard,
                        digito_agencia,
                        tipo_conta,
                        digito_conta,
                        nacionalidade,
                        tipo_registro,
                        cod_rejeicao,
                        desc_ocupacao,
                        encaminha_para,
                        data_venda,
                        data_excluido,
                        data_vencimento,
                        venda_programada,
                        campanha,
                        pago,
                        faixa_renda,
                        idligacao,
                        agravo,
                        numero_proposta_advance,
                        plano,
                        val_morte_qc,
                        data_retorno_advance});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cImport_AssociadoAsync(
                    string numero_vendas, 
                    string id_registro, 
                    string cpf, 
                    string bandeira, 
                    string num_cartao, 
                    string complemen_cartao, 
                    string dia_venc, 
                    string validade, 
                    string nome_titular, 
                    string nome_segurado, 
                    string data_nascimento, 
                    string altura, 
                    string sexo, 
                    string peso, 
                    string tipo_seguro, 
                    string val_MA, 
                    string val_IPA, 
                    string premio, 
                    string operador, 
                    string obs, 
                    string compl_benefic, 
                    string supervisor, 
                    string e_civil, 
                    string extensao, 
                    string e_mail, 
                    string ocupacao, 
                    string rg, 
                    string digito_rg, 
                    string emissor_rg, 
                    string data_emiss_rg, 
                    string master, 
                    string a_express, 
                    string visa, 
                    string diners, 
                    string filhos, 
                    string banco, 
                    string agencia, 
                    string contaban, 
                    string cobranca, 
                    string nosso_numero, 
                    string numero_lote, 
                    string cod_seguradora, 
                    string cod_produto, 
                    string status, 
                    string Obs_Rejeicao, 
                    string hipercard, 
                    string digito_agencia, 
                    string tipo_conta, 
                    string digito_conta, 
                    string nacionalidade, 
                    string tipo_registro, 
                    string cod_rejeicao, 
                    string desc_ocupacao, 
                    string encaminha_para, 
                    string data_venda, 
                    string data_excluido, 
                    string data_vencimento, 
                    string venda_programada, 
                    string campanha, 
                    string pago, 
                    string faixa_renda, 
                    string idligacao, 
                    string agravo, 
                    string numero_proposta_advance, 
                    string plano, 
                    string val_morte_qc, 
                    string data_retorno_advance) {
            this.cImport_AssociadoAsync(numero_vendas, id_registro, cpf, bandeira, num_cartao, complemen_cartao, dia_venc, validade, nome_titular, nome_segurado, data_nascimento, altura, sexo, peso, tipo_seguro, val_MA, val_IPA, premio, operador, obs, compl_benefic, supervisor, e_civil, extensao, e_mail, ocupacao, rg, digito_rg, emissor_rg, data_emiss_rg, master, a_express, visa, diners, filhos, banco, agencia, contaban, cobranca, nosso_numero, numero_lote, cod_seguradora, cod_produto, status, Obs_Rejeicao, hipercard, digito_agencia, tipo_conta, digito_conta, nacionalidade, tipo_registro, cod_rejeicao, desc_ocupacao, encaminha_para, data_venda, data_excluido, data_vencimento, venda_programada, campanha, pago, faixa_renda, idligacao, agravo, numero_proposta_advance, plano, val_morte_qc, data_retorno_advance, null);
        }
        
        /// <remarks/>
        public void cImport_AssociadoAsync(
                    string numero_vendas, 
                    string id_registro, 
                    string cpf, 
                    string bandeira, 
                    string num_cartao, 
                    string complemen_cartao, 
                    string dia_venc, 
                    string validade, 
                    string nome_titular, 
                    string nome_segurado, 
                    string data_nascimento, 
                    string altura, 
                    string sexo, 
                    string peso, 
                    string tipo_seguro, 
                    string val_MA, 
                    string val_IPA, 
                    string premio, 
                    string operador, 
                    string obs, 
                    string compl_benefic, 
                    string supervisor, 
                    string e_civil, 
                    string extensao, 
                    string e_mail, 
                    string ocupacao, 
                    string rg, 
                    string digito_rg, 
                    string emissor_rg, 
                    string data_emiss_rg, 
                    string master, 
                    string a_express, 
                    string visa, 
                    string diners, 
                    string filhos, 
                    string banco, 
                    string agencia, 
                    string contaban, 
                    string cobranca, 
                    string nosso_numero, 
                    string numero_lote, 
                    string cod_seguradora, 
                    string cod_produto, 
                    string status, 
                    string Obs_Rejeicao, 
                    string hipercard, 
                    string digito_agencia, 
                    string tipo_conta, 
                    string digito_conta, 
                    string nacionalidade, 
                    string tipo_registro, 
                    string cod_rejeicao, 
                    string desc_ocupacao, 
                    string encaminha_para, 
                    string data_venda, 
                    string data_excluido, 
                    string data_vencimento, 
                    string venda_programada, 
                    string campanha, 
                    string pago, 
                    string faixa_renda, 
                    string idligacao, 
                    string agravo, 
                    string numero_proposta_advance, 
                    string plano, 
                    string val_morte_qc, 
                    string data_retorno_advance, 
                    object userState) {
            if ((this.cImport_AssociadoOperationCompleted == null)) {
                this.cImport_AssociadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncImport_AssociadoOperationCompleted);
            }
            this.InvokeAsync("cImport_Associado", new object[] {
                        numero_vendas,
                        id_registro,
                        cpf,
                        bandeira,
                        num_cartao,
                        complemen_cartao,
                        dia_venc,
                        validade,
                        nome_titular,
                        nome_segurado,
                        data_nascimento,
                        altura,
                        sexo,
                        peso,
                        tipo_seguro,
                        val_MA,
                        val_IPA,
                        premio,
                        operador,
                        obs,
                        compl_benefic,
                        supervisor,
                        e_civil,
                        extensao,
                        e_mail,
                        ocupacao,
                        rg,
                        digito_rg,
                        emissor_rg,
                        data_emiss_rg,
                        master,
                        a_express,
                        visa,
                        diners,
                        filhos,
                        banco,
                        agencia,
                        contaban,
                        cobranca,
                        nosso_numero,
                        numero_lote,
                        cod_seguradora,
                        cod_produto,
                        status,
                        Obs_Rejeicao,
                        hipercard,
                        digito_agencia,
                        tipo_conta,
                        digito_conta,
                        nacionalidade,
                        tipo_registro,
                        cod_rejeicao,
                        desc_ocupacao,
                        encaminha_para,
                        data_venda,
                        data_excluido,
                        data_vencimento,
                        venda_programada,
                        campanha,
                        pago,
                        faixa_renda,
                        idligacao,
                        agravo,
                        numero_proposta_advance,
                        plano,
                        val_morte_qc,
                        data_retorno_advance}, this.cImport_AssociadoOperationCompleted, userState);
        }
        
        private void OncImport_AssociadoOperationCompleted(object arg) {
            if ((this.cImport_AssociadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cImport_AssociadoCompleted(this, new cImport_AssociadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cImport_Beneficiario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cImport_Beneficiario(string id_registro, string numero_vendas, string parentesco, string Nome, string Percentual, string Data_nasc, string Numero_lote, string obs, string Complemento) {
            object[] results = this.Invoke("cImport_Beneficiario", new object[] {
                        id_registro,
                        numero_vendas,
                        parentesco,
                        Nome,
                        Percentual,
                        Data_nasc,
                        Numero_lote,
                        obs,
                        Complemento});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cImport_BeneficiarioAsync(string id_registro, string numero_vendas, string parentesco, string Nome, string Percentual, string Data_nasc, string Numero_lote, string obs, string Complemento) {
            this.cImport_BeneficiarioAsync(id_registro, numero_vendas, parentesco, Nome, Percentual, Data_nasc, Numero_lote, obs, Complemento, null);
        }
        
        /// <remarks/>
        public void cImport_BeneficiarioAsync(string id_registro, string numero_vendas, string parentesco, string Nome, string Percentual, string Data_nasc, string Numero_lote, string obs, string Complemento, object userState) {
            if ((this.cImport_BeneficiarioOperationCompleted == null)) {
                this.cImport_BeneficiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncImport_BeneficiarioOperationCompleted);
            }
            this.InvokeAsync("cImport_Beneficiario", new object[] {
                        id_registro,
                        numero_vendas,
                        parentesco,
                        Nome,
                        Percentual,
                        Data_nasc,
                        Numero_lote,
                        obs,
                        Complemento}, this.cImport_BeneficiarioOperationCompleted, userState);
        }
        
        private void OncImport_BeneficiarioOperationCompleted(object arg) {
            if ((this.cImport_BeneficiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cImport_BeneficiarioCompleted(this, new cImport_BeneficiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cImport_Endereco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cImport_Endereco(string tipo_endereco, string endereco, string bairro, string uf, string cep, string Numero, string cidade, string Complemento, string id_registro, string numero_vendas, string numero_lote, string Correspondencia) {
            object[] results = this.Invoke("cImport_Endereco", new object[] {
                        tipo_endereco,
                        endereco,
                        bairro,
                        uf,
                        cep,
                        Numero,
                        cidade,
                        Complemento,
                        id_registro,
                        numero_vendas,
                        numero_lote,
                        Correspondencia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cImport_EnderecoAsync(string tipo_endereco, string endereco, string bairro, string uf, string cep, string Numero, string cidade, string Complemento, string id_registro, string numero_vendas, string numero_lote, string Correspondencia) {
            this.cImport_EnderecoAsync(tipo_endereco, endereco, bairro, uf, cep, Numero, cidade, Complemento, id_registro, numero_vendas, numero_lote, Correspondencia, null);
        }
        
        /// <remarks/>
        public void cImport_EnderecoAsync(string tipo_endereco, string endereco, string bairro, string uf, string cep, string Numero, string cidade, string Complemento, string id_registro, string numero_vendas, string numero_lote, string Correspondencia, object userState) {
            if ((this.cImport_EnderecoOperationCompleted == null)) {
                this.cImport_EnderecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncImport_EnderecoOperationCompleted);
            }
            this.InvokeAsync("cImport_Endereco", new object[] {
                        tipo_endereco,
                        endereco,
                        bairro,
                        uf,
                        cep,
                        Numero,
                        cidade,
                        Complemento,
                        id_registro,
                        numero_vendas,
                        numero_lote,
                        Correspondencia}, this.cImport_EnderecoOperationCompleted, userState);
        }
        
        private void OncImport_EnderecoOperationCompleted(object arg) {
            if ((this.cImport_EnderecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cImport_EnderecoCompleted(this, new cImport_EnderecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cImport_Cartoes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cImport_Cartoes(string id_registro, string numero_vendas, string bandeira, string num_cartao, string complemen_cartao, string dia_venc, string validade, string nome_titular) {
            object[] results = this.Invoke("cImport_Cartoes", new object[] {
                        id_registro,
                        numero_vendas,
                        bandeira,
                        num_cartao,
                        complemen_cartao,
                        dia_venc,
                        validade,
                        nome_titular});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cImport_CartoesAsync(string id_registro, string numero_vendas, string bandeira, string num_cartao, string complemen_cartao, string dia_venc, string validade, string nome_titular) {
            this.cImport_CartoesAsync(id_registro, numero_vendas, bandeira, num_cartao, complemen_cartao, dia_venc, validade, nome_titular, null);
        }
        
        /// <remarks/>
        public void cImport_CartoesAsync(string id_registro, string numero_vendas, string bandeira, string num_cartao, string complemen_cartao, string dia_venc, string validade, string nome_titular, object userState) {
            if ((this.cImport_CartoesOperationCompleted == null)) {
                this.cImport_CartoesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncImport_CartoesOperationCompleted);
            }
            this.InvokeAsync("cImport_Cartoes", new object[] {
                        id_registro,
                        numero_vendas,
                        bandeira,
                        num_cartao,
                        complemen_cartao,
                        dia_venc,
                        validade,
                        nome_titular}, this.cImport_CartoesOperationCompleted, userState);
        }
        
        private void OncImport_CartoesOperationCompleted(object arg) {
            if ((this.cImport_CartoesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cImport_CartoesCompleted(this, new cImport_CartoesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cImport_ContasAdicionais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cImport_ContasAdicionais(string id_registro, string numero_vendas, string Banco, string Agencia, string DigitoAgencia, string Conta, string DigitoConta, string TipoConta, string dia_vencimento, string nome_titular) {
            object[] results = this.Invoke("cImport_ContasAdicionais", new object[] {
                        id_registro,
                        numero_vendas,
                        Banco,
                        Agencia,
                        DigitoAgencia,
                        Conta,
                        DigitoConta,
                        TipoConta,
                        dia_vencimento,
                        nome_titular});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cImport_ContasAdicionaisAsync(string id_registro, string numero_vendas, string Banco, string Agencia, string DigitoAgencia, string Conta, string DigitoConta, string TipoConta, string dia_vencimento, string nome_titular) {
            this.cImport_ContasAdicionaisAsync(id_registro, numero_vendas, Banco, Agencia, DigitoAgencia, Conta, DigitoConta, TipoConta, dia_vencimento, nome_titular, null);
        }
        
        /// <remarks/>
        public void cImport_ContasAdicionaisAsync(string id_registro, string numero_vendas, string Banco, string Agencia, string DigitoAgencia, string Conta, string DigitoConta, string TipoConta, string dia_vencimento, string nome_titular, object userState) {
            if ((this.cImport_ContasAdicionaisOperationCompleted == null)) {
                this.cImport_ContasAdicionaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OncImport_ContasAdicionaisOperationCompleted);
            }
            this.InvokeAsync("cImport_ContasAdicionais", new object[] {
                        id_registro,
                        numero_vendas,
                        Banco,
                        Agencia,
                        DigitoAgencia,
                        Conta,
                        DigitoConta,
                        TipoConta,
                        dia_vencimento,
                        nome_titular}, this.cImport_ContasAdicionaisOperationCompleted, userState);
        }
        
        private void OncImport_ContasAdicionaisOperationCompleted(object arg) {
            if ((this.cImport_ContasAdicionaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cImport_ContasAdicionaisCompleted(this, new cImport_ContasAdicionaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cImport_Telefone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cImport_Telefone(string id_registro, string numero_vendas, string tipo, string ddd, string telefone, string ramal, string numero_lote) {
            object[] results = this.Invoke("cImport_Telefone", new object[] {
                        id_registro,
                        numero_vendas,
                        tipo,
                        ddd,
                        telefone,
                        ramal,
                        numero_lote});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cImport_TelefoneAsync(string id_registro, string numero_vendas, string tipo, string ddd, string telefone, string ramal, string numero_lote) {
            this.cImport_TelefoneAsync(id_registro, numero_vendas, tipo, ddd, telefone, ramal, numero_lote, null);
        }
        
        /// <remarks/>
        public void cImport_TelefoneAsync(string id_registro, string numero_vendas, string tipo, string ddd, string telefone, string ramal, string numero_lote, object userState) {
            if ((this.cImport_TelefoneOperationCompleted == null)) {
                this.cImport_TelefoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OncImport_TelefoneOperationCompleted);
            }
            this.InvokeAsync("cImport_Telefone", new object[] {
                        id_registro,
                        numero_vendas,
                        tipo,
                        ddd,
                        telefone,
                        ramal,
                        numero_lote}, this.cImport_TelefoneOperationCompleted, userState);
        }
        
        private void OncImport_TelefoneOperationCompleted(object arg) {
            if ((this.cImport_TelefoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cImport_TelefoneCompleted(this, new cImport_TelefoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cIncluir_Indicacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cIncluir_Indicacao(string Indicado_Por, string Nome_Indicado, string DDD, string Telefone, string Estado, string Cidade) {
            object[] results = this.Invoke("cIncluir_Indicacao", new object[] {
                        Indicado_Por,
                        Nome_Indicado,
                        DDD,
                        Telefone,
                        Estado,
                        Cidade});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cIncluir_IndicacaoAsync(string Indicado_Por, string Nome_Indicado, string DDD, string Telefone, string Estado, string Cidade) {
            this.cIncluir_IndicacaoAsync(Indicado_Por, Nome_Indicado, DDD, Telefone, Estado, Cidade, null);
        }
        
        /// <remarks/>
        public void cIncluir_IndicacaoAsync(string Indicado_Por, string Nome_Indicado, string DDD, string Telefone, string Estado, string Cidade, object userState) {
            if ((this.cIncluir_IndicacaoOperationCompleted == null)) {
                this.cIncluir_IndicacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncIncluir_IndicacaoOperationCompleted);
            }
            this.InvokeAsync("cIncluir_Indicacao", new object[] {
                        Indicado_Por,
                        Nome_Indicado,
                        DDD,
                        Telefone,
                        Estado,
                        Cidade}, this.cIncluir_IndicacaoOperationCompleted, userState);
        }
        
        private void OncIncluir_IndicacaoOperationCompleted(object arg) {
            if ((this.cIncluir_IndicacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cIncluir_IndicacaoCompleted(this, new cIncluir_IndicacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cExcluir_Telefone_Maxivida", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cExcluir_Telefone_Maxivida(string DDD, string Telefone, string CPF) {
            object[] results = this.Invoke("cExcluir_Telefone_Maxivida", new object[] {
                        DDD,
                        Telefone,
                        CPF});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cExcluir_Telefone_MaxividaAsync(string DDD, string Telefone, string CPF) {
            this.cExcluir_Telefone_MaxividaAsync(DDD, Telefone, CPF, null);
        }
        
        /// <remarks/>
        public void cExcluir_Telefone_MaxividaAsync(string DDD, string Telefone, string CPF, object userState) {
            if ((this.cExcluir_Telefone_MaxividaOperationCompleted == null)) {
                this.cExcluir_Telefone_MaxividaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncExcluir_Telefone_MaxividaOperationCompleted);
            }
            this.InvokeAsync("cExcluir_Telefone_Maxivida", new object[] {
                        DDD,
                        Telefone,
                        CPF}, this.cExcluir_Telefone_MaxividaOperationCompleted, userState);
        }
        
        private void OncExcluir_Telefone_MaxividaOperationCompleted(object arg) {
            if ((this.cExcluir_Telefone_MaxividaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cExcluir_Telefone_MaxividaCompleted(this, new cExcluir_Telefone_MaxividaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cVerificaSenha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cVerificaSenha(string matricula, string senha) {
            object[] results = this.Invoke("cVerificaSenha", new object[] {
                        matricula,
                        senha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cVerificaSenhaAsync(string matricula, string senha) {
            this.cVerificaSenhaAsync(matricula, senha, null);
        }
        
        /// <remarks/>
        public void cVerificaSenhaAsync(string matricula, string senha, object userState) {
            if ((this.cVerificaSenhaOperationCompleted == null)) {
                this.cVerificaSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncVerificaSenhaOperationCompleted);
            }
            this.InvokeAsync("cVerificaSenha", new object[] {
                        matricula,
                        senha}, this.cVerificaSenhaOperationCompleted, userState);
        }
        
        private void OncVerificaSenhaOperationCompleted(object arg) {
            if ((this.cVerificaSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cVerificaSenhaCompleted(this, new cVerificaSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cBuscaFonesLogProspectsFones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable cBuscaFonesLogProspectsFones(string NumeroVendas) {
            object[] results = this.Invoke("cBuscaFonesLogProspectsFones", new object[] {
                        NumeroVendas});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void cBuscaFonesLogProspectsFonesAsync(string NumeroVendas) {
            this.cBuscaFonesLogProspectsFonesAsync(NumeroVendas, null);
        }
        
        /// <remarks/>
        public void cBuscaFonesLogProspectsFonesAsync(string NumeroVendas, object userState) {
            if ((this.cBuscaFonesLogProspectsFonesOperationCompleted == null)) {
                this.cBuscaFonesLogProspectsFonesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncBuscaFonesLogProspectsFonesOperationCompleted);
            }
            this.InvokeAsync("cBuscaFonesLogProspectsFones", new object[] {
                        NumeroVendas}, this.cBuscaFonesLogProspectsFonesOperationCompleted, userState);
        }
        
        private void OncBuscaFonesLogProspectsFonesOperationCompleted(object arg) {
            if ((this.cBuscaFonesLogProspectsFonesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cBuscaFonesLogProspectsFonesCompleted(this, new cBuscaFonesLogProspectsFonesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdvanceConsultaRetorno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AdvanceConsultaRetorno(string numerosolicitacao, string codigoCliente) {
            object[] results = this.Invoke("AdvanceConsultaRetorno", new object[] {
                        numerosolicitacao,
                        codigoCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AdvanceConsultaRetornoAsync(string numerosolicitacao, string codigoCliente) {
            this.AdvanceConsultaRetornoAsync(numerosolicitacao, codigoCliente, null);
        }
        
        /// <remarks/>
        public void AdvanceConsultaRetornoAsync(string numerosolicitacao, string codigoCliente, object userState) {
            if ((this.AdvanceConsultaRetornoOperationCompleted == null)) {
                this.AdvanceConsultaRetornoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdvanceConsultaRetornoOperationCompleted);
            }
            this.InvokeAsync("AdvanceConsultaRetorno", new object[] {
                        numerosolicitacao,
                        codigoCliente}, this.AdvanceConsultaRetornoOperationCompleted, userState);
        }
        
        private void OnAdvanceConsultaRetornoOperationCompleted(object arg) {
            if ((this.AdvanceConsultaRetornoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdvanceConsultaRetornoCompleted(this, new AdvanceConsultaRetornoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WhatsAppSend", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WhatsAppSend(string Telefone, string msg) {
            object[] results = this.Invoke("WhatsAppSend", new object[] {
                        Telefone,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WhatsAppSendAsync(string Telefone, string msg) {
            this.WhatsAppSendAsync(Telefone, msg, null);
        }
        
        /// <remarks/>
        public void WhatsAppSendAsync(string Telefone, string msg, object userState) {
            if ((this.WhatsAppSendOperationCompleted == null)) {
                this.WhatsAppSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhatsAppSendOperationCompleted);
            }
            this.InvokeAsync("WhatsAppSend", new object[] {
                        Telefone,
                        msg}, this.WhatsAppSendOperationCompleted, userState);
        }
        
        private void OnWhatsAppSendOperationCompleted(object arg) {
            if ((this.WhatsAppSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WhatsAppSendCompleted(this, new WhatsAppSendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cEnviaXMLAdvance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cEnviaXMLAdvance(string Xml) {
            object[] results = this.Invoke("cEnviaXMLAdvance", new object[] {
                        Xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cEnviaXMLAdvanceAsync(string Xml) {
            this.cEnviaXMLAdvanceAsync(Xml, null);
        }
        
        /// <remarks/>
        public void cEnviaXMLAdvanceAsync(string Xml, object userState) {
            if ((this.cEnviaXMLAdvanceOperationCompleted == null)) {
                this.cEnviaXMLAdvanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OncEnviaXMLAdvanceOperationCompleted);
            }
            this.InvokeAsync("cEnviaXMLAdvance", new object[] {
                        Xml}, this.cEnviaXMLAdvanceOperationCompleted, userState);
        }
        
        private void OncEnviaXMLAdvanceOperationCompleted(object arg) {
            if ((this.cEnviaXMLAdvanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cEnviaXMLAdvanceCompleted(this, new cEnviaXMLAdvanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void Cancelamento_PropostaCompletedEventHandler(object sender, Cancelamento_PropostaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cancelamento_PropostaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Cancelamento_PropostaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TefMaximidiaCompletedEventHandler(object sender, TefMaximidiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TefMaximidiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TefMaximidiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Cod_Retorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string Seq_Tef {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TefMaximidiaCancelamentoCompletedEventHandler(object sender, TefMaximidiaCancelamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TefMaximidiaCancelamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TefMaximidiaCancelamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TefInformacaoCompletedEventHandler(object sender, TefInformacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TefInformacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TefInformacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Cod_retorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public double Valor_Enviado {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string Seq_Tef {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string pago {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TefVerifica_ClienteCompletedEventHandler(object sender, TefVerifica_ClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TefVerifica_ClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TefVerifica_ClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cImport_AssociadoCompletedEventHandler(object sender, cImport_AssociadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cImport_AssociadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cImport_AssociadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cImport_BeneficiarioCompletedEventHandler(object sender, cImport_BeneficiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cImport_BeneficiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cImport_BeneficiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cImport_EnderecoCompletedEventHandler(object sender, cImport_EnderecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cImport_EnderecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cImport_EnderecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cImport_CartoesCompletedEventHandler(object sender, cImport_CartoesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cImport_CartoesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cImport_CartoesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cImport_ContasAdicionaisCompletedEventHandler(object sender, cImport_ContasAdicionaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cImport_ContasAdicionaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cImport_ContasAdicionaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cImport_TelefoneCompletedEventHandler(object sender, cImport_TelefoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cImport_TelefoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cImport_TelefoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cIncluir_IndicacaoCompletedEventHandler(object sender, cIncluir_IndicacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cIncluir_IndicacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cIncluir_IndicacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cExcluir_Telefone_MaxividaCompletedEventHandler(object sender, cExcluir_Telefone_MaxividaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cExcluir_Telefone_MaxividaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cExcluir_Telefone_MaxividaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cVerificaSenhaCompletedEventHandler(object sender, cVerificaSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cVerificaSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cVerificaSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cBuscaFonesLogProspectsFonesCompletedEventHandler(object sender, cBuscaFonesLogProspectsFonesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cBuscaFonesLogProspectsFonesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cBuscaFonesLogProspectsFonesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AdvanceConsultaRetornoCompletedEventHandler(object sender, AdvanceConsultaRetornoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdvanceConsultaRetornoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdvanceConsultaRetornoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void WhatsAppSendCompletedEventHandler(object sender, WhatsAppSendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhatsAppSendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WhatsAppSendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void cEnviaXMLAdvanceCompletedEventHandler(object sender, cEnviaXMLAdvanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cEnviaXMLAdvanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cEnviaXMLAdvanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591